export function downloadReport(analysis, inputType) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const date = new Date().toLocaleDateString('en-IN');
    const margin = 20;
    const pageWidth = 210;
    const contentWidth = pageWidth - margin * 2;
    let y = 30;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(124, 58, 237);
    doc.text('Xylar AI Portfolio Analyzer', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(date, pageWidth - margin, y, { align: 'right' });
    y += 6;
    doc.setDrawColor(232, 228, 223);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    const sections = [
        ['01  Portfolio Summary', analysis.portfolio_summary],
        ['02  Key Observations', analysis.key_observations],
        ['03  Diversification', analysis.diversification_concentration],
        ['04  Risks & Red Flags', analysis.risks_red_flags],
        ['05  Improvement Opportunities', analysis.improvement_opportunities],
        ['06  Final Takeaway', analysis.final_takeaway],
    ];

    sections.forEach(([title, content]) => {
        if (y > 260) { doc.addPage(); y = 20; }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(124, 58, 237);
        doc.text(title, margin, y);
        y += 6;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(55, 65, 81);
        const lines = doc.splitTextToSize(content || '—', contentWidth);
        lines.forEach(line => {
            if (y > 272) { doc.addPage(); y = 20; }
            doc.text(line, margin, y);
            y += 5.5;
        });
        y += 8;
    });

    // Footer on last page
    doc.setFontSize(8);
    doc.setTextColor(160, 168, 176);
    const footer = 'Generated by Xylar · This is an AI-generated analysis, not financial advice.';
    doc.text(footer, pageWidth / 2, 285, { align: 'center' });

    doc.save(`Xylar_Portfolio_Analysis_${date.replace(/\//g, '-')}.pdf`);
}
